### ISSUE TITLE
Lister les films et les series

### ISSUE THREAD

**Issue by RedHotMan** [ESGI-Influenceur/Movizer#2]
- Liste des films et séries avec ces informations:
    - [x] Titre
    - [ ] Titre original
    - [x] Poster
    - [ ] Genre(s)
    - [x] Synopris `overview` 
    - [ ] Date de sortie (film) | Date de premiére diffusion (séries)

**Comment by gurnavdeep** [comment]
Au niveau de la "Liste" de films et series, seul le titre, le synopsis, le poster et potentiellement la date de sortie seront implémenter.
Faut -il faire apparaitre d'autres infos également au niveau de la liste ?
Car le genre, titre-original, runtime etc... pourront etre renseigné au niveau du detail film/series.

**Comment by RedHotMan** [comment]
Yes, tu as raison. 
L'utilisateur découvrir ça au moment ou il s'interessera à un film en particulier
